#!/usr/bin/env zsh

STOW_FOLDERS="bin,nvim,tmux,zsh"

mkdir -p $HOME/.config/nvim
mkdir -p $HOME/.config/tmux
mkdir -p $HOME/.local/scripts

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	echo "stow $folder"
	stow -D $folder -t $HOME
	stow $folder -t $HOME
done
